### ISSUE TITLE
Support for Android SDK/NDK for old unity versions

### ISSUE THREAD

**Issue by mashuk999** [Unity-CI/docker#39]
**Bug description**
 Unity hub do not configure ndk and sdk for older unity versions so we need to manually configure ndk and sdk for them. 

**How to reproduce**
Make a android build with il2cpp using 2018.4.18f1

**Expected behavior**
Build should be successful. Also sdk and ndk should be found

**Additional details**
Unity hub only configure ndk and sdk after unity versions 2019.x. So older versions need to be configured manually

**Comment by webbertakken** [comment]
These are steep demands, especially for a 0.x version. I'll mark this as an enhancement instead.

**Comment by GabLeRoux** [comment]
Unless Unity decides to manually fix it on their own with a new version of `hub`, the way to fix this will be a bit harder.

Like it or not, a good way to fix this is to upgrade your unity version ;)

We can still add ideas here to fix this for a future version of the docker images.

On disord, Abhay said:

> We can find the supported version of ndk from unity editor maybe. If you go to preferences and click on download ndk it redirect you to the supported ndk and start to download it

quoting myself:

> A manual solution for older versions may be acceptable, but will need to be clearly documented and also, maybe someone will need to try it for each versions unless we find a way to automate this for all earlier versions. At least, providing instructions will allow people to send fixes for specific versions.

This also implies we could provide instructions to maybe setup the NDK, JDK and SDK on top of existing image at least as a workaround. Suggestions are welcome and you're also all invited to try things and share findings here. ;)

**Comment by mashuk999** [comment]
We can put a disclaimer about the supported version untill we have a workaround. Since many people are in 2018 and waiting for new images. Untill the release of new builder they can migrate to new versions. Also since 2018 is supported untill 2022 only I don't think unity is going to anything from their end.

**Comment by webbertakken** [comment]
@mashuk999 As stated above, we'll treat this as an enhancement rather than a bug as there's a lot of work to be done, and nobody is claiming that the version is above v1.0.

Please consider anything before 2019.3 to be nice to have. The work to be done is fully dependent on contributions from the community.

Please also note that we're not affiliated with Unity themselves. We're not an official solution and we don't have the same support standards as they do. We're just a few open source contributors who try to make CI for Unity easier and work out for everyone.

That said. You're entirely free to contribute the required parts to support older versions, and we'll support your efforts to do so, given that the solutions are required, scalable and work for everyone.

**Comment by mashuk999** [comment]
Ya that's why i was saying to put a disclaimer in the readme about it so that people wont spam in discord and issues about this. I am just saying 2018 is a old version. Ok i will make a PR on unity-builder adding that info. Is that fine?

**Comment by GabLeRoux** [comment]
Maybe we could add a section to the website for some general explanation for docker images:  
https://unity-ci.com/docs

**Comment by mashuk999** [comment]
That will be much better

**Comment by webbertakken** [comment]
Please review
